get_follow_optim_cost: true
get_length_cost: true
get_map_collision: true
get_similarity_cost: true
ittc_thres: 1.0
lh_grid_lb: 0.6
lh_grid_rows: 3
lh_grid_ub: 1.2
map_ext: .png
map_path: E:\ESE 599\f1tenth_safe_racing\safe_racing\es_src\configs\General1\General1_map
optim_path: E:\ESE 599\f1tenth_safe_racing\safe_racing\es_src\configs\General1\optim.pkl
params_dict:
  '0': speed
  '1': max_curvature
  '2': length
  '3': similarity
  '4': follow_optim
  '5': abs_speed_reward
  '6': curvature_speed_punish
  '7': opponent_collision
params_name: !!python/tuple
- traj_v_scale
- cost_weights
params_num: !!python/tuple
- 1
- 7
rollout_states: !!python/tuple
- rollout_obs
- rollout_ego_s
- rollout_opp_s
- ego_best_traj_idx
- opp_best_traj_idx
- ego_prev_traj
- ego_prev_opp
- ego_ittc
- ego_control_error
- abs_ittc
scan_num: 108
tracker: advanced_pure_pursuit
tracker_config_path: E:\ESE 599\f1tenth_safe_racing\safe_racing\es_src\configs\General1\pure_pursuit_config.yaml
tracker_steps: 10
traj_num: 33
traj_points: 15
traj_v_scale: 1.0
traj_v_span_max: 1.0
traj_v_span_min: 0.2
traj_v_span_num: 5
weights_num: 7
wpt_ctline_path: E:\ESE 599\f1tenth_safe_racing\safe_racing\es_src\configs\General1\centerline.csv
wpt_delim: ;
wpt_path: E:\ESE 599\f1tenth_safe_racing\safe_racing\es_src\configs\General1\traj_race_cl.csv
wpt_rowskip: 2
