avoid_buffer: 15
avoid_dist: 5
follow_v_scale: 0.85
ittc_thres: 1.0
lane_occupied_dist: 0.3
lanesFileName: !!python/tuple
- lane_1_optim.csv
- lane_2_optim.csv
lanesFiles: !!python/tuple
- ../configs/General1/lane_1_optim.csv
- ../configs/General1/lane_2_optim.csv
lanesNum: 2
map_ext: .png
map_path: ../configs/General1/General1_map
scan_num: 108
slowdown_buffer: 10
slowdown_v_scale: 0.8
tracker: advanced_pure_pursuit
tracker_config_path: ../configs/General1/pure_pursuit_config.yaml
tracker_steps: 10
traj_v_scale: 1.0
wpt_delim: ;
wpt_path: ../configs/General1/traj_race_cl.csv
wpt_rowskip: 3
