D: 2
Lscale: 8.0
Pscale: 8.0
debug: false
interpScale: 10
map_ext: .png
map_path: ../configs/General1/General1_map
maxL: 1.5
maxP: 0.6
minL: 0.5
minP: 0.4
vel_scale: 1.0
wpt_delim: ;
wpt_path: ../configs/General1/traj_race_cl.csv
wpt_rowskip: 2
wpt_vind: 5
wpt_xind: 1
wpt_yind: 2
