change_collision_cost: true
get_length_cost: true
get_map_collision: true
get_max_curvature: false
get_mean_curvature: true
get_obstacle_collision: true
get_similarity_cost: true
get_vel_cost: true
map_ext: .png
map_path: /home/zzjun/Documents/objective_space/obj_space_planning/es_src/configs/Spielberg/Spielberg_map
tracker: advanced_pure_pursuit
tracker_config_path: /home/zzjun/Documents/objective_space/obj_space_planning/es_src/configs/Spielberg/pure_pursuit_config.yaml
traj_v_span_max: 1.0
traj_v_span_min: 0.5
traj_v_span_num: 5
wpt_ctline_path: /home/zzjun/Documents/objective_space/obj_space_planning/es_src/configs/Spielberg/centerline.csv
wpt_delim: ;
wpt_path: /home/zzjun/Documents/objective_space/obj_space_planning/es_src/configs/Spielberg/traj_race_cl.csv
wpt_rowskip: 2
