D: 0.2
Lscale: 8.0
Pscale: 8.0
interpScale: 10
debug: true
map_ext: .png
map_path: /home/zzjun/Documents/objective_space/obj_space_planning/es_src/configs/Spielberg/Spielberg_map
maxL: 1.8
maxP: 0.8
minL: 0.5
minP: 0.5
vel_scale: 1.0
wpt_delim: ;
wpt_path: /home/zzjun/Documents/objective_space/obj_space_planning/es_src/configs/Spielberg/traj_race_cl.csv
wpt_rowskip: 2
wpt_vind: 5
wpt_xind: 1
wpt_yind: 2
